CustomerPortal/CustomerPortal/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerPortal.Models;
using CustomerPortal.ViewModels;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;

namespace CustomerPortal.Controllers
{
    public partial class CustomerController : Controller
    {
//        [Demo]
//        public ActionResult Editing_Popup()
//        {
//            return View();
//        }
        public ActionResult Index()
        {
            return View();
        }
//
        public ActionResult EditingPopup_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(CustomerService.Read().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditingPopup_Create([DataSourceRequest] DataSourceRequest request, Customer customer)
        {
            DbSingleton.GetDb().Customers.Add(customer);
            DbSingleton.GetDb().SaveChanges();
            return Json(CustomerService.Read().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditingPopup_Update([DataSourceRequest] DataSourceRequest request, Customer customer)
        {
            DbSingleton.GetDb().Customers.AddOrUpdate(customer);
            DbSingleton.GetDb().SaveChanges();
            return Json(CustomerService.Read().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditingPopup_Destroy([DataSourceRequest] DataSourceRequest request, Customer _customer)
        {
            Customer customer = DbSingleton.GetDb().Customers.FirstOrDefault(x => x.CustID == _customer.CustID);
            if (customer != null)
            {
                DbSingleton.GetDb().Customers.Remove(customer);
                DbSingleton.GetDb().SaveChanges();
            }
            
            return Json(CustomerService.Read().ToDataSourceResult(request));
        }



    }
}

CustomerPortal/CustomerPortal/Controllers/ReservationController.cs
using CustomerPortal.ViewModels;
using System.Web.Mvc;
using CustomerPortal.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
 
namespace CustomerPortal.Controllers
{
    public partial class ReservationController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult EditingPopup_Read([DataSourceRequest] DataSourceRequest request)
        {
            return Json(Reservation.Read().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditingPopup_Create([DataSourceRequest] DataSourceRequest request, Reservation reservation)
        {
            return Json(Reservation.Read().ToDataSourceResult(request));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditingPopup_Update([DataSourceRequest] DataSourceRequest request, Reservation reservation)
        {

            if (ModelState.IsValid) { 
                Reservation res = DbSingleton.GetDb().Reservations.Find(reservation.ReservationCode);
                res.NoGuests = reservation.NoGuests;
                res.NoRooms = reservation.NoRooms;
                res.CheckInDate = reservation.CheckInDate;
                res.CheckOutDate = reservation.CheckOutDate;

                DbSingleton.GetDb().SaveChanges();
            }
            return Json(Reservation.Read().ToDataSourceResult(request, ModelState));
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult EditingPopup_Destroy([DataSourceRequest] DataSourceRequest request, Reservation reservation)
        {
            //            Reservation.DeleteReservation(reservation);
            Reservation res = DbSingleton.GetDb().Reservations.Find(reservation.ReservationCode);
            DbSingleton.GetDb().Reservations.Remove(res);
            DbSingleton.GetDb().SaveChanges();

            return Json(Reservation.Read().ToDataSourceResult(request));
        }

        /*
        public static void DeleteReservation(Reservation reservation)
        {
            Reservation res = DbSingleton.GetDb().Reservations.Find(reservation.ReservationCode);
            DbSingleton.GetDb().Reservations.Remove(res);
            DbSingleton.GetDb().SaveChanges();
        }

        public static void UpdateReservation(Reservation reservation)
        {
            Reservation res = DbSingleton.GetDb().Reservations.Find(reservation.ReservationCode);
            res.NoGuests = reservation.NoGuests;
            res.NoRooms = reservation.NoRooms;
            res.CheckInDate = reservation.CheckInDate;
            res.CheckOutDate = reservation.CheckOutDate;

            DbSingleton.GetDb().SaveChanges();
        }
        */

    }
}

CustomerPortal/CustomerPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    <link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.common-material.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.mobile.all.min.css" rel="stylesheet" type="text/css" />
    <link href="https://kendo.cdn.telerik.com/2018.1.221/styles/kendo.material.min.css" rel="stylesheet" type="text/css" />
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/jquery.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/jszip.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.all.min.js"></script>
    <script src="https://kendo.cdn.telerik.com/2018.1.221/js/kendo.aspnetmvc.min.js"></script>
    <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Customer Portal", "Index", "Home",  new { @class = "navbar-brand" })
            </div>
           <div class="navbar-collapse collapse"> 
               <ul class="nav navbar-nav"> 
                   <li>@Html.ActionLink("Book Room", "BookRoom", "Home")
                    <li>@Html.ActionLink("All Customers", "Index", "Customer")
                    @*                    <li>@Html.ActionLink("Contact", "Contact", "Home")*@
                    <li >@Html.ActionLink("Check Reservations", "Index", "Reservation")</li>
                </ul>
               
            </div> 
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>